
name: Deploy Flask Backend to Oracle Cloud

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main                             

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            cd backend
            chmod +x run.sh
            screen -S flaskapp -X quit || true
            screen -S flaskapp -dm bash ./run.sh
          EOF
             
